#!/usr/bin/env bun
/**
 * Build-time asset manifest generator.
 *
 * Scans `public/assets/{chains,formats}_transparent/` for files matching
 * `<value>_<label>.png` and emits `src/utils/assets.generated.ts`.
 *
 * - `value`: stable identifier — ASCII lowercase letters, digits, hyphens. Used as picker `value`.
 * - `label`: free-form display string (Korean, spaces, special chars allowed). What the user sees.
 *
 * Run via `bun scripts/generate-asset-manifest.ts` (auto-fires on predev/prebuild).
 */
import { readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = join(import.meta.dir, '..');
const CHAINS_DIR = join(ROOT, 'public/assets/chains_transparent');
const FORMATS_DIR = join(ROOT, 'public/assets/formats_transparent');
const OUT = join(ROOT, 'src/utils/assets.generated.ts');

const FILENAME = /^([a-z0-9][a-z0-9-]*)_(.+)\.png$/;

interface Entry {
  value: string;
  label: string;
  file: string;
}

function scan(dir: string, kind: string): Entry[] {
  const files = readdirSync(dir)
    .filter((f) => !f.startsWith('.') && f.toLowerCase().endsWith('.png'))
    .sort();
  const seen = new Map<string, string>();
  return files.map((file) => {
    const m = FILENAME.exec(file);
    if (!m) {
      throw new Error(
        `[asset-manifest] ${kind}/${file} violates <value>_<label>.png — must contain a single underscore separating a lowercase value ([a-z0-9-]+) and a non-empty label, followed by .png.`,
      );
    }
    const prev = seen.get(m[1]);
    if (prev) {
      throw new Error(
        `[asset-manifest] duplicate value "${m[1]}" in ${kind}: ${prev} vs ${file}. Each value must be unique.`,
      );
    }
    seen.set(m[1], file);
    return { value: m[1], label: m[2], file };
  });
}

const chains = scan(CHAINS_DIR, 'chains_transparent');
const formats = scan(FORMATS_DIR, 'formats_transparent');

const fmt = (entries: Entry[]): string =>
  entries
    .map(
      (e) =>
        `  { value: ${JSON.stringify(e.value)}, label: ${JSON.stringify(e.label)}, file: ${JSON.stringify(e.file)} },`,
    )
    .join('\n');

const body = `// AUTO-GENERATED by scripts/generate-asset-manifest.ts — DO NOT EDIT.
// Source of truth: file names under public/assets/{chains,formats}_transparent/.
// Regenerate via \`bun scripts/generate-asset-manifest.ts\` (or just re-run \`bun run dev\`/\`build\`).

export interface AssetEntry {
  readonly value: string;
  readonly label: string;
  readonly file: string;
}

export const CHAIN_ASSETS = [
${fmt(chains)}
] as const satisfies readonly AssetEntry[];

export const FORMAT_ASSETS = [
${fmt(formats)}
] as const satisfies readonly AssetEntry[];
`;

writeFileSync(OUT, body);
console.log(
  `[asset-manifest] chains: ${chains.length}, formats: ${formats.length} → ${OUT.replace(ROOT + '/', '')}`,
);
